### ISSUE TITLE
Documentation Roadmap

### ISSUE THREAD

**Issue by bhamodi** [optimizely/nuclear-js#105]
Hey @jordangarcia, just thought it'd be nice to have a place to document our progress on the documentation website. I've added this list of things to be done, please feel free to update this list.
- [x] Create landing page.
- [ ] Create interactive example.
- [ ] Get a NuclearJS domain and create a CNAME file.
- [ ] Create general documentation page explaining flux methodologies.
- [ ] Create documentation page explaining NuclearJS methodologies and structure.
- [ ] Reduce content in the README file and make it more like a quick summary of NuclearJS.

**Comment by jordangarcia** [comment]
:+1:

**Comment by sidereus7** [comment]
I would love a React-Router example for Nuclear. That would be so helpful!!

**Comment by wesleyyee** [comment]
+1 
Especially React-router 1.0 isomorphic example

**Comment by rawberg** [comment]
It would be great to have an example with Vue.js or Riot.js. Is the [nuclear-vue-mixin](https://github.com/jordangarcia/nuclear-vue-mixin) still compatible with the latest versions of Vue and Nuclear?

**Comment by iansinnott** [comment]
It would be great to see some updated docs :+1:. The existing docs were quite helpful when I was first getting started, but it was the [rest-api][] example that really helped me out when I started building more complex stuff with Nuclear.

[rest-api]: https://github.com/optimizely/nuclear-js/tree/master/examples/rest-api

I think the community could see some big wins if some of the knowledge that currently exists in the examples was made more prominent in the documentation.
